### ISSUE TITLE
Error: failed to check for existing tunnels

### ISSUE THREAD

**Issue by web-padawan** [saucelabs/node-saucelabs#102]
I'm using `@web/test-runner-saucelabs` and today my builds started to fail with the following error:

```
[Saucelabs] Setting up Sauce Connect proxy...
3 Nov 15:19:00 - Sauce Connect 4.6.2, build 5183 ad61662

3 Nov 15:19:00 - REST: Using CA certificate bundle /usr/local/etc/openssl/cert.pem.
3 Nov 15:19:00 - REST: Using CA certificate verify path /etc/ssl/certs.

3 Nov 15:19:00 - TUNNEL: Using CA certificate bundle /usr/local/etc/openssl/cert.pem.

3 Nov 15:19:00 - TUNNEL: Using CA certificate verify path /etc/ssl/certs.

3 Nov 15:19:00 - Starting up; pid 96701

3 Nov 15:19:00 - Command line arguments: /Users/XXXX/vaadin/vaadin-time-picker-new/node_modules/saucelabs/build/.sc-v4.6.2/bin/sc --tunnel-identifier=web-test-runner-632c299d-5745-4809-89a9-9f6250d86cf2 --no-ssl-bump-domains=127.0.0.1,localhost,10.64.12.198 --user=XXXXXX-XXXXXXXX --api-key=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX --rest-url=https://api.us-west-1.saucelabs.com/rest/v1

3 Nov 15:19:00 - Log file: /var/folders/45/94scl3_d1wx4lslst2rv0jq80000gn/T/sc-web-test-runner-632c299d-5745-4809-89a9-9f6250d86cf2.log

3 Nov 15:19:00 - Pid file: /tmp/sc_client-web-test-runner-632c299d-5745-4809-89a9-9f6250d86cf2.pid
3 Nov 15:19:00 - Timezone: EET GMT offset: 2h

3 Nov 15:19:00 - Using no proxy for connecting to Sauce Labs REST API.

3 Nov 15:19:01 - Started scproxy on port 53014.

3 Nov 15:19:01 - Please wait for 'you may start your tests' to start your tests.

3 Nov 15:19:03 - failed to check for existing tunnels

3 Nov 15:19:03 - Sauce Connect could not establish a connection.
3 Nov 15:19:03 - Please check your firewall and proxy settings.

Error while running tests:
Error: 3 Nov 15:19:03 - Sauce Connect could not establish a connection.
3 Nov 15:19:03 - Please check your firewall and proxy settings.

    at Socket.<anonymous> (/Users/sergey/vaadin/vaadin-time-picker-new/node_modules/saucelabs/build/index.js:318:25)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

Build example: https://github.com/vaadin/vaadin-time-picker/pull/168/checks?check_run_id=1347582686

Note, the repository also has other job (visual regression tests) that uses [legacy URL](https://github.com/web-padawan/hermione-sauce/blob/f9b00b18f45477bb4891b363cbb3cb6c7bfa1203/lib/sauce.js#L19) and it works fine:
https://github.com/vaadin/vaadin-time-picker/pull/168/checks?check_run_id=1347582625

**Comment by christian-bromann** [comment]
@web-padawan is this an issue that happened due to an update of `saucelabs` or with any versions? I will reach out to our @saucelabs/scdev team to get more infos on this.

**Comment by web-padawan** [comment]
It's unclear what could be the reason but not the tests are passing:
https://github.com/vaadin/vaadin-time-picker/pull/168/checks?check_run_id=1347805157

So maybe it was some random failure (although it happened several times for different repositories).

Thank you for prompt feedback, for now I'm closing this as it seems to be fixed.

**Comment by christian-bromann** [comment]
@web-padawan ok, let me know if this happens again, maybe with the help of the log files we can investigate this issue better. Thanks!

**Comment by web-padawan** [comment]
Unfortunately today the builds started to fail again with the same issue:

https://github.com/vaadin/vaadin-select/pull/234/checks?check_run_id=1351738065

https://github.com/vaadin/vaadin-upload/pull/360/checks?check_run_id=1351734013

The `saucelabs` version installed is the latest one (4.5.1), see the log example below (I removed the access key).

```
2020-11-04 10:22:37.055 [4824] Sauce Connect 4.6.2, build 5183 ad61662 
2020-11-04 10:22:37.055 [4824] REST: Using CA certificate bundle /usr/local/etc/openssl/cert.pem.
2020-11-04 10:22:37.055 [4824] REST: Using CA certificate verify path /etc/ssl/certs.
2020-11-04 10:22:37.055 [4824] TUNNEL: Using CA certificate bundle /usr/local/etc/openssl/cert.pem.
2020-11-04 10:22:37.055 [4824] TUNNEL: Using CA certificate verify path /etc/ssl/certs.
2020-11-04 10:22:37.056 [4824] Trying to autodetect proxy settings
2020-11-04 10:22:37.063 [4824] Starting up; pid 4824
2020-11-04 10:22:37.063 [4824] Command line arguments: /Users/sergey/vaadin/vaadin-upload-new/node_modules/saucelabs/build/.sc-v4.6.2/bin/sc --tunnel-identifier=web-test-runner-40d87e62-cb18-4b69-9e35-df931821a51c --no-ssl-bump-domains=127.0.0.1,localhost,10.64.12.198 --user=vaadin-upload --api-key=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX --rest-url=https://api.us-west-1.saucelabs.com/rest/v1 
2020-11-04 10:22:37.063 [4824] Log file: /var/folders/45/94scl3_d1wx4lslst2rv0jq80000gn/T/sc-web-test-runner-40d87e62-cb18-4b69-9e35-df931821a51c.log
2020-11-04 10:22:37.063 [4824] Pid file: /tmp/sc_client-web-test-runner-40d87e62-cb18-4b69-9e35-df931821a51c.pid
2020-11-04 10:22:37.063 [4824] Timezone: EET GMT offset: 2h
2020-11-04 10:22:37.071 [4824] Using no proxy for connecting to Sauce Labs REST API.
2020-11-04 10:22:38.150 [4824] PROXY *** scproxy started ***
2020-11-04 10:22:38.152 [4824] PROXY found DNS server 10.64.1.3
2020-11-04 10:22:38.152 [4824] PROXY found DNS server 10.64.1.2
2020-11-04 10:22:38.196 [4824] Started scproxy on port 56467.
2020-11-04 10:22:38.196 [4824] Please wait for 'you may start your tests' to start your tests.
2020-11-04 10:22:39.298 [4824] failed to check for existing tunnels
2020-11-04 10:22:39.299 [4824] Sauce Connect could not establish a connection.
2020-11-04 10:22:39.299 [4824] Please check your firewall and proxy settings.
2020-11-04 10:22:39.300 [4824] Goodbye.
```

**Comment by christian-bromann** [comment]
@web-padawan please update to latest package version. It should be fixed now. If not let me know and I will re-open.

**Comment by web-padawan** [comment]
Updated to `4.5.2` and my builds are passing now, thanks for the quick fix! 🙇‍♂️
