### ISSUE TITLE
Failure on M1 Mac: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by web-padawan** [saucelabs/node-saucelabs#115]
Hello,

On my MacBook M1 there is a following error when using [`@web/test-runner-saucelabs`](https://github.com/modernweb-dev/web/tree/master/packages/test-runner-saucelabs):

```
Error: fatal error: unexpected signal during runtime execution

    at Socket.<anonymous> (/Users/serhii/vaadin/web-components/node_modules/saucelabs/build/index.js:307:16)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

Any ideas what the reason could be?

**Comment by christian-bromann** [comment]
> Any ideas what the reason could be?

mhm 🤔  not really .. seems to be a common problem with M1 chips

**Comment by web-padawan** [comment]
Here is a log file (credentials removed). Looks like something is wrong with the certificate not present in the keychain:

```
2021-05-25 10:28:34.936 [63611] Sauce Connect 4.6.4, build 5309 21ce484 
2021-05-25 10:28:34.937 [63611] REST: Using CA certificate bundle /private/etc/ssl/cert.pem.
2021-05-25 10:28:34.937 [63611] REST: Using CA certificate verify path /etc/ssl/certs.
2021-05-25 10:28:34.937 [63611] TUNNEL: Using CA certificate bundle /private/etc/ssl/cert.pem.
2021-05-25 10:28:34.937 [63611] TUNNEL: Using CA certificate verify path /etc/ssl/certs.
2021-05-25 10:28:34.937 [63611] Trying to autodetect proxy settings
2021-05-25 10:28:34.949 [63611] Serving metrics on 8888
2021-05-25 10:28:34.950 [63611] Starting up; pid 63611
2021-05-25 10:28:34.950 [63611] Command line arguments: /Users/serhii/vaadin/web-components/node_modules/saucelabs/build/.sc-v4.6.4/bin/sc --logfile=./sauce-labs-connect.log --tunnel-identifier=web-test-runner-bc5a541e-eefc-4c94-86a0-3714b994a361 --no-ssl-bump-domains=127.0.0.1,localhost,10.64.XX.XX --user=XXXXX --api-key=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX --rest-url=https://saucelabs.com/rest/v1 
2021-05-25 10:28:34.950 [63611] Log file: ./sauce-labs-connect.log
2021-05-25 10:28:34.950 [63611] Pid file: /tmp/sc_client-web-test-runner-bc5a541e-eefc-4c94-86a0-3714b994a361.pid
2021-05-25 10:28:34.950 [63611] Timezone: EEST GMT offset: 3h
2021-05-25 10:28:34.952 [63611] Using no proxy for connecting to Sauce Labs REST API.
2021-05-25 10:28:36.005 [63611] ***********************************************************
2021-05-25 10:28:36.005 [63611] INFO: Validating Sauce Connect Proxy 4.6.4 for darwin-amd64.
2021-05-25 10:28:36.005 [63611] ***********************************************************
2021-05-25 10:28:36.005 [63611] ***********************************************************
2021-05-25 10:28:36.005 [63611] WARNING: Outdated version 4.6.4. Please download the latest version from https://saucelabs.com/downloads/sc-4.6.5-osx.zip
2021-05-25 10:28:36.005 [63611] ***********************************************************
2021-05-25 10:28:36.062 [63611] Started scproxy on port 64123.
2021-05-25 10:28:36.062 [63611] Please wait for 'you may start your tests' to start your tests.
2021-05-25 10:28:50.949 [63611] Secure remote tunnel provisioned. Tunnel ID: XXXXX
2021-05-25 10:28:51.708 [63611] Starting OCSP certificate check.
2021-05-25 10:28:51.726 [63611] Using no proxy for connecting to http://status.geotrust.com.
2021-05-25 10:28:51.827 [63611] Using no proxy for connecting to http://ocsp.digicert.com.
2021-05-25 10:28:51.853 [63611] Reached a trusted CA. Certificate chain is verified.
2021-05-25 10:28:51.855 [63611] Using no proxy for connecting to tunnel VM.
2021-05-25 10:28:51.862 [63611] Selenium listener disabled.
2021-05-25 10:28:51.863 [63611] Establishing secure TLS connection to tunnel...
2021-05-25 10:28:52.063 [63611] MAIN OpenSSL error finding MacOS certs: /System/Library/Keychains/SystemRootCertificates.keychain
2021-05-25 10:28:52.067 [63611] MAIN The specified item could not be found in the keychain.
```

**Comment by christian-bromann** [comment]
@web-padawan ah you are using Sauce Connect? Mind trying Sauce Connect `v4.6.5`? If you clear you node_modules and re-install your dependencies you should automatically get the latest version.

**Comment by web-padawan** [comment]
I was able to solve this by installing [Worldwide Developer Relations - G2 Certificate](https://www.apple.com/certificateauthority/AppleWWDRCAG2.cer).

**Comment by christian-bromann** [comment]
Ah nice. Closing then!
