### ISSUE TITLE
Response code 404 when downloading sc-4.6.5-linux32.tar.gz

### ISSUE THREAD

**Issue by web-padawan** [saucelabs/node-saucelabs#116]
```
GotError [HTTPError]: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/home/runner/work/web-components/web-components/node_modules/download/node_modules/got/index.js:482:24)
    at EventEmitter.emit (events.js:376:20)
    at EventEmitter.emit (domain.js:470:12)
    at getResponse (/home/runner/work/web-components/web-components/node_modules/download/node_modules/got/index.js:320:5)
    at Immediate.<anonymous> (/home/runner/work/web-components/web-components/node_modules/download/node_modules/got/index.js:147:6)
    at processImmediate (internal/timers.js:462:21) {
  host: 'saucelabs.com',
  hostname: 'saucelabs.com',
  method: 'GET',
  path: '/downloads/sc-4.6.5-linux32.tar.gz',
  protocol: 'https:',
  url: 'https://saucelabs.com/downloads/sc-4.6.5-linux32.tar.gz',
  statusCode: 404,
  statusMessage: 'Not Found',
  headers: {
    server: 'nginx',
    date: 'Tue, 25 May 2021 08:34:30 GMT',
    'content-type': 'text/html; charset=utf-8',
    'transfer-encoding': 'chunked',
    connection: 'close',
    'content-encoding': 'gzip'
  }
}
```

See https://github.com/vaadin/web-components/pull/1990#issuecomment-847671384 for more details.

**Comment by christian-bromann** [comment]
According to the [Sauce Connect changelog](https://changelog.saucelabs.com/en/sauce-connect-proxy-version-) there is no Linux 32bit version anymore. Can you run GitHub actions on a 64bit version?

**Comment by christian-bromann** [comment]
I will revert the last release and make it a major version bump.

**Comment by christian-bromann** [comment]
> * Create another valid 4.7.7 release that's basically 4.7.5 again. This will make npm/yarn install 4.7.7 instead of 4.7.6.

Good call, thanks!

**Comment by christian-bromann** [comment]
Done, please let me know if the issue still occurs. Thanks for reporting.

**Comment by HackbrettXXX** [comment]
Thanks for reacting so quickly. While npm will now automatically install 4.7.7 this doesn't seem to resolve the issue. I'm still getting a 404:

```
{ HTTPError: Response code 404 (Not Found)
    at EventEmitter.ee.on.res (/home/travis/build/MrRio/jsPDF/node_modules/download/node_modules/got/index.js:482:24)
    at EventEmitter.emit (events.js:198:13)
    at EventEmitter.emit (domain.js:448:20)
    at getResponse (/home/travis/build/MrRio/jsPDF/node_modules/download/node_modules/got/index.js:320:5)
    at Immediate.setImmediate (/home/travis/build/MrRio/jsPDF/node_modules/download/node_modules/got/index.js:147:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
  name: 'HTTPError',
  host: 'saucelabs.com',
  hostname: 'saucelabs.com',
  method: 'GET',
  path: '/downloads/sc-4.6.5-linux32.tar.gz',
  protocol: 'https:',
  url: 'https://saucelabs.com/downloads/sc-4.6.5-linux32.tar.gz',
  statusCode: 404,
  statusMessage: 'Not Found',
  headers:
   { server: 'nginx',
     date: 'Thu, 27 May 2021 12:16:56 GMT',
     'content-type': 'text/html; charset=utf-8',
     'transfer-encoding': 'chunked',
     connection: 'close',
     'content-encoding': 'gzip' } }
```

**Comment by christian-bromann** [comment]
@HackbrettXXX you will have to upgrade to v5 of this package where the 32bit version got removed.

**Comment by christian-bromann** [comment]
I just triggered a release of a new v4 that will default to Sauce Connect v4.6.4 rather than latest. This should finally fix your issue.

**Comment by HackbrettXXX** [comment]
Ah, thanks. That's good, because upgrading would not be that easy for us, since we use saucelabs indirectly via `karma-sauce-launcher`.

**Comment by HackbrettXXX** [comment]
I've just tested it, 4.7.8 works fine. Thanks again for fixing it so quickly.
