### ISSUE TITLE
Periodic ENOENT running in CI

### ISSUE THREAD

**Issue by nathancahill** [saucelabs/node-saucelabs#86]
This is an error that happens >50% of the time on CircleCI. No changes are made between one run and the next. One run might pass, the next will fail with this error. All versions are committed in yarn.lock.

```js
12 06 2020 08:29:13.851:ERROR [SaucelabsLauncher]: Error: spawn /home/circleci/repo/node_modules/saucelabs/build/.sc-v4.5.4/bin/sc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

{
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/circleci/repo/node_modules/saucelabs/build/.sc-v4.5.4/bin/sc',
  path: '/home/circleci/repo/node_modules/saucelabs/build/.sc-v4.5.4/bin/sc',
  spawnargs: [ '--version' ],
  killed: false,
  stdout: '',
  stderr: '',
  failed: true,
  signal: null,
  cmd: '/home/circleci/repo/node_modules/saucelabs/build/.sc-v4.5.4/bin/sc --version',
  timedOut: false
}
```

**Comment by christian-bromann** [comment]
@nathancahill can you try to run the pipeline without cache? I am afraid that the cache that includes the Sauce Connect binary is used for different environments.

**Comment by christian-bromann** [comment]
ping @nathancahill

**Comment by nathancahill** [comment]
Thanks, I think removing the cache solved the issue. I'll reopen in the future if it reappears.

**Comment by nathancahill** [comment]
Even with the cache disabled we're still getting periodic errors.

**Comment by Sam55555** [comment]
The error occurred too on each run after gitlab runner cached on gitlab ci using the docker executer. No error during the first run and clean cache.

**Comment by enriquegh** [comment]
Haven't been able to reproduce on a private Gitlab instance with a docker runner so far.

I was able to reproduce, however, if I was using the node alpine image:
```
 $ NODE_OPTIONS=--trace-warnings ts-node index.ts
Error: spawn /builds/enrique/sauce-sc-example/node_modules/saucelabs/build/.sc-v4.5.4/bin/sc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /builds/enrique/sauce-sc-example/node_modules/saucelabs/build/.sc-v4.5.4/bin/sc',
  path: '/builds/enrique/sauce-sc-example/node_modules/saucelabs/build/.sc-v4.5.4/bin/sc',
  spawnargs: [ '--version' ],
  killed: false,
  stdout: '',
  stderr: '',
  failed: true,
  signal: null,
  cmd: '/builds/enrique/sauce-sc-example/node_modules/saucelabs/build/.sc-v4.5.4/bin/sc --version',
  timedOut: false
}
```
This gave an error 100% of the time though and not intermittently.

**Comment by enriquegh** [comment]
From @joventuraz:
```
it looks like the node module is not available, if there happened to be more than one concurrent build and one is finishing and cleaning up, it might affect the other build if they are using the same workspace which it seems like they might from the path in the error
```

Adding to this I think the issue lies somewhere in bin-wrapper and how it does its checks for the file/folder.

It seems like bin-wrapper is a collection of small modules so it was a bit hard to pinpoint exactly what is missing.

Some things we could try and do:
- Do more checks on whether the binary is actually there or not and retry to download if its not
- Allow for users to specify a folder where sc should be looked for and the user can download this manually
- use something other than bin-wrapper since it seems to not be very active

**Comment by christian-bromann** [comment]
I proposed a change in the Sauce Connect Launcher to retry starting Sauce Connect if it fails: https://github.com/karma-runner/karma-sauce-launcher/pull/219

Let's see if we can fix this issue with that.

**Comment by christian-bromann** [comment]
@nathancahill have you experienced the same issue after updating the package?

**Comment by Seamoo13** [comment]
Are there any updates on this? I am also having this issue
![sauceConnectIssue](https://user-images.githubusercontent.com/47522152/108216247-eb05cd80-713a-11eb-8a40-f9d01e920c39.png)

**Comment by markcellus** [comment]
I'm having this issue too using Node 14 alpine (14.16.1). But is no longer an issue after downgrading node back to 12.

**Comment by Seamoo13** [comment]
The issue went away for my project for a few months, then suddenly returned and is occurring roughly 50% of the time.

![2021-07-02_3](https://user-images.githubusercontent.com/47522152/124270194-8f196f80-db44-11eb-9640-6f027a0587c3.png)

**Comment by LeParadoxHD** [comment]
Any update on this?

**Comment by enriquegh** [comment]
@wswebcreation would [7.1.3](https://github.com/saucelabs/node-saucelabs/releases/tag/7.1.3) fix this as bin-wrapper is now replaced?

**Comment by wswebcreation** [comment]
Hi @enriquegh 

I'm not 100% sure, we simplified the download now, so it's worth a try

**Comment by enriquegh** [comment]
I've re-opened this as it's essentially the same issue as before.
Looks like we replaced `bin-wrapper` for the `download` module ([link](https://www.npmjs.com/package/download)).

We have something that in theory checks for the binary to be there so not sure why this is happening.

**Comment by kleinbs** [comment]
We are running into the same issue here running in an alpine docker container. Is this still being worked on, or is there a good work around?

```
Execution of 2 workers started at 2023-01-20T17:59:03.464Z
2023-01-20T17:59:03.526Z DEBUG @wdio/utils:initialiseServices: initialise service "sauce" as NPM package
2023-01-20T17:59:04.939Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-01-20T17:59:04.942Z INFO @wdio/sauce-service: Starting Sauce Connect Tunnel
Error: spawn /builds/consumer-identity/OneID/infra-eng/infra-source-bundles/my-account/e2e/node_modules/saucelabs/build/sc-loader/.sc-v4.8.0/bin/sc ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /builds/consumer-identity/OneID/infra-eng/infra-source-bundles/my-account/e2e/node_modules/saucelabs/build/sc-loader/.sc-v4.8.0/bin/sc',
  path: '/builds/consumer-identity/OneID/infra-eng/infra-source-bundles/my-account/e2e/node_modules/saucelabs/build/sc-loader/.sc-v4.8.0/bin/sc',
  spawnargs: [
    '--verbose',
    '--logfile=-',
    '--no-autodetect',
    '--tunnel-name=SC-tunnel-40602318395085324',
    '--no-ssl-bump-domains=127.0.0.1,localhost,1[72](https://gitlab.disney.com/consumer-identity/OneID/infra-eng/infra-source-bundles/my-account/-/jobs/18227172#L72).17.0.3',
    '--user=MyAccountTestRunner',
    '--api-key=7ee95499-d176-4eed-ace0-0c83a4ec6e[74](https://gitlab.disney.com/consumer-identity/OneID/infra-eng/infra-source-bundles/my-account/-/jobs/18227172#L74)',
    '--region=us-west-1'
  ]
}
```

**Comment by naruaway** [comment]
I think probably this is one of the root cause https://github.com/saucelabs/node-saucelabs/pull/241

**Comment by budziam** [comment]
This should be resolved in the latest version 9, which adds support for SC5 and drops support for SC4.
