### ISSUE TITLE
TypeError: Expected the `options.agent` properties to be `http`, `https` or `http2`, got `options`

### ISSUE THREAD

**Issue by christian-bromann** [saucelabs/node-saucelabs#87]
Upgraded from v5 to v6 latest. With an internal proxy under corporate net in the config file seeing the below error.

2020-06-15T03:32:04.663Z ERROR @wdio/utils:initialiseServices: TypeError: Expected the `options.agent` properties to be `http`, `https` or `http2`, got `options`
    at Function.normalizeArguments (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/got/dist/source/core/index.js:561:27)

**To Reproduce**
- Install wdio as its mentioned at https://webdriver.io/docs/gettingstarted.html
- Install @wdio/sauce-service
- Provide a proxy in the wdio.conf.js along with sauce labs credentials

**Expected behavior**
No errors

**Log**
Execution of 1 spec files started at 2020-06-15T03:32:04.592Z

2020-06-15T03:32:04.663Z ERROR @wdio/utils:initialiseServices: TypeError: 
```
Expected the `options.agent` properties to be `http`, `https` or `http2`, got `options`
    at Function.normalizeArguments (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/got/dist/source/core/index.js:561:27)
    at Function.normalizeArguments (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/got/dist/source/as-promise/core.js:34:31)
    at mergeOptions (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/got/dist/source/as-promise/core.js:108:47)
    at Function.got.extend.instancesOrOptions [as extend] (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/got/dist/source/create.js:127:22)
    at new SauceLabs (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/saucelabs/build/index.js:46:32)
    at new SauceLauncher (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/@wdio/sauce-service/build/launcher.js:28:16)
    at initialiseLauncherService (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/@wdio/utils/build/initialiseServices.js:61:31)
    at Launcher.run (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/@wdio/cli/build/launcher.js:73:48)
    at launch (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/@wdio/cli/build/commands/run.js:138:19)
    at handler (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/@wdio/cli/build/commands/run.js:171:12)
```

**Additional context**
As this error pops up, @wdio/saucelabs doesn't update the test name (sauce.context step/script)
`(COMMAND executeScript("sauce:context=webdriver.io page - should have the right title", <object>))`

**Comment by Sam55555** [comment]
Hello,
i have the same error in the last version 4.1.5 of the karma-sauce-launcher and defined HTTP_PROXY variable on gitlab.

**Comment by kscully** [comment]
Hello,

this happens also when I run the following below. Can you please raise the priority on this as nobody behind a corporate proxy can run automated tests.

Thanks

--------------------------------------------------------

```
HTTP_PROXY=http://fromCommandLine:8080 HTTPS_PROXY=https://fromCommandLine:8080 TEST_ENV=DEV npm run test-aws

> mercer-testframework-wdio-template@1.0.0 test-aws C:\Users\keith-scully\WebstormProjects\botfLerna\packages-gbp\health-gbp\health-gbp-main-ta
> wdio wdio.sauce.conf.js --tag=@debug


Execution of 1 spec files started at 2020-06-18T09:15:46.967Z

2020-06-18T09:15:47.252Z ERROR @wdio/utils:initialiseServices: TypeError: Expected the `options.agent` properties to be `http`, `https` or `http2`, got `options`
    at Function.normalizeArguments (C:\Users\keith-scully\WebstormProjects\botfLerna\packages-gbp\health-gbp\health-gbp-main-ta\node_modules\got\dist\source\core\index.js:552:27)
    at Function.normalizeArguments (C:\Users\keith-scully\WebstormProjects\botfLerna\packages-gbp\health-gbp\health-gbp-main-ta\node_modules\got\dist\source\as-promise\core.js:34:31)
    at mergeOptions (C:\Users\keith-scully\WebstormProjects\botfLerna\packages-gbp\health-gbp\health-gbp-main-ta\node_modules\got\dist\source\as-promise\core.js:108:47)
    at Function.got.extend (C:\Users\keith-scully\WebstormProjects\botfLerna\packages-gbp\health-gbp\health-gbp-main-ta\node_modules\got\dist\source\create.js:127:22)
    at new SauceLabs (C:\Users\keith-scully\WebstormProjects\botfLerna\packages-gbp\health-gbp\health-gbp-main-ta\node_modules\saucelabs\build\index.js:46:32)
    at new SauceLauncher (C:\Users\keith-scully\WebstormProjects\botfLerna\packages-gbp\health-gbp\health-gbp-main-ta\node_modules\@wdio\sauce-service\build\launcher.js:28:16)
    at initialiseLauncherService (C:\Users\keith-scully\WebstormProjects\botfLerna\packages-gbp\health-gbp\health-gbp-main-ta\node_modules\@wdio\utils\build\initialiseServices.js:61:31)

```


--------------------------------------------------------
